node:
  enabled: true
  node:
    chain: dev
    flags:
    - "--rpc-external"
    - "--alice"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
userUri: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
externalDscpIpfs:
  host: localhost
  port: 3000
externalDscpIdentity:
  host: localhost
  port: 3000
