apiVersion: v2
name: dscp-api
# renovate: image=digicatapult/dscp-api
appVersion: '5.0.3'
description: A Helm chart for dscp-api
version: '4.9.0'
type: application
dependencies:
  - name: dscp-node
    version: '4.5.6'
    repository: https://digicatapult.github.io/helm-charts/
    condition: node.enabled
    alias: node
  - name: dscp-ipfs
    version: '3.0.6'
    repository: https://digicatapult.github.io/helm-charts/
    condition: ipfs.enabled
    alias: ipfs
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
