# fullNameOverride:
config:
  port: 80
  # externalOrigin: "http://localhost:3000" # Overrides the server url in the openapi spec
  # externalPathPrefix: "alice/dscp-api" # Path prefix to be applied to served API routes
  logLevel: info
  accountKey: //Alice
  # externalIpfsHost: "" # This overrides dscpIpfs.enabled when setting the IPFS_HOST envar
  # externalIpfsPort: 5001 # This overrides dscpIpfs.enabled when setting the IPFS_PORT envar
  enableLivenessProbe: true
  substrateStatusPollPeriodMs: 10000
  substrateStatusTimeoutMs: 2000
  ipfsStatusPollPeriodMs: 10000
  ipfsStatusTimeoutMs: 2000
  auth:
    type: NONE
    jwksUri: https://inteli.eu.auth0.com/.well-known/jwks.json
    audience: inteli-dev
    issuer: https://inteli.eu.auth0.com/
    tokenUrl: https://inteli.eu.auth0.com/oauth/token

deployment:
  annotations: {}
  replicaCount: 1

ingress:
  host: ""
  annotations: {}
  className: ""
  enabled: true
  paths:
    - /v3

service:
  annotations: {}
  enabled: true
  port: 80

image:
  repository: digicatapult/dscp-api
  pullPolicy: IfNotPresent
  tag: 'v4.8.4'

dscpNode:
  enabled: false

dscpIpfs:
  enabled: true
  dscpNode:
    enabled: true
