apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wasp-ws-reading-service.fullname" . }}
  labels:
    {{- include "wasp-ws-reading-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "wasp-ws-reading-service.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        name: {{ include "wasp-ws-reading-service.fullname" . }}
    spec:
      {{- include "wasp-ws-reading-service.imagePullSecrets" . | indent 6 }}
      initContainers:
        - name: {{ include "wasp-ws-reading-service.initNotifications.name" . }}
          image: {{ .Values.kafkaInit.repository }}:{{ .Values.kafkaInit.tag }}
          envFrom:
            - configMapRef:
                name: {{ include "wasp-ws-reading-service.fullname" . }}-config
          command: ['/bin/sh', '-c']
          args: ['/opt/bitnami/kafka/bin/kafka-topics.sh --create --topic $(kafkaNotificationReadingsTopic) --bootstrap-server=$(kafkaBrokers) --partitions $(notificationsPartitions) --replication-factor $(notificationsReplicationFactor) --if-not-exists']
      containers:
        - name: {{ include "wasp-ws-reading-service.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ws-reading-service.fullname" . }}-config
                  key: port
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ws-reading-service.fullname" . }}-config
                  key: logLevel
            - name: WS_PING_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ws-reading-service.fullname" . }}-config
                  key: wsPingIntervalMs
            - name: KAFKA_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ws-reading-service.fullname" . }}-config
                  key: kafkaLogLevel
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ws-reading-service.fullname" . }}-config
                  key: kafkaBrokers
            - name: KAFKA_NOTIFICATION_READINGS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ws-reading-service.fullname" . }}-config
                  key: kafkaNotificationReadingsTopic

