{{- $prepend  := .Values.prepend -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: openapi-merger
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  openapi-merge.yaml: |
    inputs:
    - inputFile: base.json
    {{- range .Values.paths }}
    - inputURL: {{ . }}
    {{- if (not (empty $prepend)) }}
      pathModification:
        prepend: {{ $prepend  }}
    {{- end }}
    {{- end }}
    output: {{ .Values.output }}
  base.json: |
    {
      "openapi": "3.0.3",
      "info": {
        "title": {{ .Values.openApiTitle | quote }},
        "version": "0.0.1"
      },
      "servers": [
        {{- range $index, $element := .Values.baseUrl }}
        {
        "url": {{ $element | toJson }}
        }{{- if ne $index (sub (len $.Values.baseUrl) 1) }},{{- end }}
        {{- end }}
      {{- if eq .Values.security.type "bearer" }}
      ],
      "components": {
        "securitySchemes": {
          "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
          }
        }
      },
      "security": [{ "BearerAuth": [] }]
      {{- else if eq .Values.security.type "oauth2" }}
      ],
      "components": {
        "securitySchemes": {
          "oAuth2AuthCode": {
            "type": "oauth2",
            "flows": {
                "authorizationCode": {
                  "authorizationUrl": {{ .Values.security.oauth2.authorizationUrl | quote }},
                  "tokenUrl": {{ .Values.security.oauth2.tokenUrl | quote }},
                  "scopes": {{ .Values.security.oauth2.scopes | toJson | default "{}" }}
              }
            }
          }
        }
      },
      "security": [{ "oAuth2AuthCode": [] }]
      {{- else }}
      ]
      {{- end }}
    }
