apiVersion: v2
name: dscp-node
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
description: A Helm chart to deploy DSCP nodes
type: application
version: 4.5.6
# renovate: image=digicatapult/dscp-node
appVersion: '4.6.0'
