annotations:
  category: dscp
  licenses: Apache-2.0
apiVersion: v2
# renovate: image=digicatapult/dscp-matchmaker-api
appVersion: v1.2.1
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - name: dscp-node
    alias: node
    repository: https://digicatapult.github.io/helm-charts/
    tags:
      - dscp-node
    version: 5.x.x
    condition: node.enabled
description: The dscp-matchmaker-api is a component of the DSCP (Digital-Supply-Chain-Platform), a blockchain platform.
home: https://github.com/digicatapult/dscp-documentation
icon: https://raw.githubusercontent.com/digicatapult/dscp-documentation/main/assets/icon.png
keywords:
  - DSCP
maintainers:
  - name: digicatapult  # Digital Catapult
    url: https://github.com/digicatapult/helm-charts
    email: opensource@digicatapult.org.uk
name: dscp-matchmaker-api
sources:
  - https://github.com/digicatapult/dscp-matchmaker-api
version: 0.0.4
