apiVersion: v2
name: inteli-api
# renovate: image=digicatapult/inteli-api
appVersion: '1.29.1'
description: A Helm chart for inteli-api
version: '1.30.0'
type: application
deprecated: true
dependencies:
  - name: postgresql
    version: '^11.9.10'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
