annotations:
  category: wasp
  licenses: Apache-2.0
apiVersion: v2
# renovate: image=digicatapult/wasp-open-api
appVersion: 0.1.4
dependencies:
  - condition: apiDocsMock.enabled
    name: nginx
    alias: apiDocsMockOne
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
  - condition: apiDocsMock.enabled
    name: nginx
    alias: apiDocsMockTwo
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
deprecated: true
description: The wasp-open-api is a component of the WASP (Wide-Area-Sensor-Platform), an IoT platform designed to normalise and consolidate data from multiple IoT data services into one place.
home: https://github.com/digicatapult/wasp-documentation
icon: https://raw.githubusercontent.com/digicatapult/wasp-documentation/main/assets/icon.png
keywords:
  - IoT
name: wasp-open-api
sources:
  - https://github.com/digicatapult/wasp-open-api
version: 1.2.2
