apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp-event-service.fullname" . }}-secret
  labels:
    {{- include "wasp-event-service.labels" . | nindent 4 }}
data:
  dbPassword: {{ .Values.postgresql.auth.password | b64enc | quote }}
  dbUsername: {{ .Values.postgresql.auth.username | b64enc | quote }}
