apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp-user-service.fullname" . }}-secret
  labels:
    {{- include "wasp-user-service.labels" . | nindent 4 }}
data:
  dbPassword: {{ .Values.postgresql.auth.password | b64enc | quote }}
  dbUsername: {{ .Values.postgresql.auth.username | b64enc | quote }}
  {{ if .Values.config.init.adminPassword.enabled -}}
  initAdminPassword: {{ .Values.config.init.adminPassword.password | b64enc | quote }}
  {{- end }}
