apiVersion: v2
name: dscp-identity-service
appVersion: '1.8.2'
description: A Helm chart for dscp-identity-service
version: '1.8.2'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
dependencies:
  - name: postgresql
    version: '^11.9.10'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: dscp-node
    version: '4.5.3'
    repository: https://digicatapult.github.io/helm-charts/
    condition: dscpNode.enabled
    alias: dscpNode
