config:
  # externalNodeHost: "" # This overrides dscpNode.enabled when setting the API_HOST envar
  port: 80
  # externalOrigin: "http://localhost:3000" # Overrides the server url in the openapi spec
  # externalPathPrefix: "alice/dscp-identity-service" # Path prefix to be applied to served API routes
  logLevel: info
  dbName: dscp
  dbPort: 5432
  # dev wallet address
  selfAddress: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
  auth:
    type: NONE

deployment:
  annotations: {}
  livenessProbe:
    enabled: true
  replicaCount: 1

ingress:
  host: "dscp-identity-service.local"
  annotations: {}
  className: ""
  enabled: true
  paths:
    - /v1/members

service:
  annotations: {}
  enabled: true
  port: 80

image:
  repository: digicatapult/dscp-identity-service
  pullPolicy: IfNotPresent
  tag: 'v1.8.12'

postgresql:
  enabled: true
  auth:
    database: dscp
    username: identity_service
    password: postgres
dscpNode:
  enabled: true
