apiVersion: v2
name: dscp-ipfs
appVersion: '2.9.3'
description: A Helm chart for veritable-ipfs
version: '2.9.4'
type: application
dependencies:
  - name: dscp-node
    version: '4.5.4'
    repository: https://digicatapult.github.io/helm-charts/
    condition: dscpNode.enabled
    alias: dscpNode
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
