# fullNameOverride:
config:
  healthCheckPort: 80
  healthCheckPollPeriod: 30000
  healthCheckTimeout: 2000
  # nodeHost: "" # This overrides dscpNode.enabled
  # nodePort:
  # publicKey:
  # privateKey:
  logLevel: info
  ipfsApiPort: 5001
  ipfsSwarmPort: 4001
  ipfsDataPath: '/ipfs'
  ipfsCommand: '/usr/local/bin/ipfs'
  ipfsArgs:
    - daemon
    - '--migrate'
  # ipfsBootNodeAddress: /dnsaddr/blah.test.com/p2p/PeerId # Valid Format for this is /multiaddr/PeerId see https://github.com/multiformats/multiaddr
  ipfsLogLevel: info
  ipfsSwarmAddrFilters:
    - /ip4/100.64.0.0/ipcidr/10
    - /ip4/169.254.0.0/ipcidr/16
    - /ip4/172.16.0.0/ipcidr/12
    - /ip4/192.0.0.0/ipcidr/24
    - /ip4/192.0.2.0/ipcidr/24
    - /ip4/192.168.0.0/ipcidr/16
    - /ip4/198.18.0.0/ipcidr/15
    - /ip4/198.51.100.0/ipcidr/24
    - /ip4/203.0.113.0/ipcidr/24
    - /ip4/240.0.0.0/ipcidr/4
    - /ip6/100::/ipcidr/64
    - /ip6/2001:2::/ipcidr/48
    - /ip6/2001:db8::/ipcidr/32
    - /ip6/fc00::/ipcidr/7
    - /ip6/fe80::/ipcidr/10

service:
  swarm:
    annotations: {}
    enabled: true
    port: 4001
  api:
    annotations: {}
    enabled: true
    port: 5001

statefulSet:
  annotations: {}
  livenessProbe:
    enabled: true

image:
  repository: digicatapult/dscp-ipfs
  pullPolicy: IfNotPresent
  tag: 'v2.9.1'

storage:
  storageClass: ''
  dataVolumeSize: 1  # in Gigabytes

dscpNode:
  enabled: true
